# This is a basic workflow that is manually triggered

name: tests-auth

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm i && npm run test:ci
      
